# 06/05
services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf #sobrescrever as config default com as nossas
    ports:
      - 80:80
    networks:
      - app-network
  php:
    image: php:8.3.4-fpm
    volumes:
      - .:/var/www #arquivos devem estar exatamente no mesmo diretório
    networks: # se não estiver no mesmo, não é possível que um ache o caminho do outro
      - app-network

networks:
  app-network:
    driver: bridge
