<!-- <p>ESSA É A VIEW DRINKS -> INDEX.PHTML</p> -->
<div class="drink-container">
    <div class="drink-header">
        <p>seu menu de</p>
        <h1>Drinks cadastrados</h1>
        <button type="submit" class="btn btn-primary mb-3">Adicionar drink</button>
    </div>
    <div class="drink-body">
        Cards...
    </div>
    <div class="drink-paginator">
        Paginator...
    </div>
</div>