<div class="container">
    <div class="d-flex justify-content-between align-items-center">
        <h1><?= $drink->name ?></h1>
        <div class="d-flex align-items-center">
            <a href="<?= route('drinks.edit', ['drink_id' => $drink->id]) ?>"><i class="bi bi-pencil-square text-secondary-custom fs-2 me-3"></i></a>
            <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#deleteModal">
                <i class="ni ni-trash3 text-danger-custom fs-2"></i>
            </button>
        </div>
    </div>

   <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Detalhes do Drink</h5>
                    <p class="card-text">
                        <strong>Nome:</strong> <?= htmlspecialchars($drink->name) ?>
                    </p>
                    <p class="card-text">
                        <strong>Preço:</strong> R$ <?= number_format($drink->price, 2, ',', '.') ?>
                    </p>
                    <p class="card-text">
                        <strong>ID do Admin:</strong> <?= htmlspecialchars($drink->admin_id) ?>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <!-- Aqui pode entrar uma galeria de fotos do drink no futuro -->
            <div class="card">
                <div class="card-body text-center" style="height: 150px; display: grid; place-items: center;">
                    <div>
                        <i class="bi bi-image" style="font-size: 3rem; color: #ccc;"></i>
                        <p class="text-muted">Galeria (em breve)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal de Confirmação da Exclusão -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirmar Exclusão</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Você tem certeza de que deseja excluir este drink? Esta ação não pode ser desfeita.</p>
        <p class="text-danger-custom">Todos os dados vinculados ao drink serão excluídos!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <form action="<?= route('drinks.destroy', ['drink_id' => $drink->id,]) ?>" method="POST" id="deleteDrinkForm">
          <input type="hidden" name="_method" value="DELETE">
          <button type="submit" class="btn btn-danger">Deletar</button>
        </form>
      </div>
    </div>
  </div>

</div>