<form action="/login" method="POST">
    <h2 class="form-title">Olá, bora pedir um drink?</h2>
    <div class="mb-4">
        <input type="email" class="form-control" placeholder="Endereço de email" id="user_email" name="user[email]">
    </div>
    <div class="mb-4">
        <input type="password" class="form-control" placeholder="Senha" id="user_password" name="user[password]">
    </div>
    <button type="submit" class="btn btn-primary mb-3">Fazer login</button>
</form>