<!DOCTYPE html>
    <html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Calibar</title>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="/assets/js/application.js"></script>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />

        <link rel="stylesheet" href="/assets/css/global.css">
        <link rel="stylesheet" href="/assets/css/dashboard.css">
    </head>

    <body>
        <aside class="sidebar">
            <div class="menu-container">
                <div class="img-container">
                    <img class="profile-img" src="<?php echo $imagePath; ?>" alt="Foto de perfil">
                    <div class="user-identification">
                        <h2>
                            <?php echo ' Olá ' . $this->current_user->name . ' :) '?>
                        </h2>
                        <h2 class="user-role">
                            <?php echo $this->current_user->isAdmin() ? 'Administrador' : 'Cliente'; ?>
                        </h2>
                    </div>
                </div>
                <div class="sidebar-menu-options">
                        <a class="sidebar-menu-items" href="#">
                            <span class="material-symbols-outlined">
                                account_circle
                        </span>
                        Meu Perfil</a>
                        <a class="sidebar-menu-items" href="<?= route('admin.index') ?>">
                            <span class="material-symbols-outlined">
                                home
                        </span>
                        Dashboard</a>
                        <a class="sidebar-menu-items" href="#">
                            <span class="material-symbols-outlined">
                                settings
                            </span>
                        Configurações</a>
                    <?php if ($this->current_user->isAdmin()): ?>
                        <a class="sidebar-menu-items" href="<?= route('drinks.index') ?>">
                            <span class="material-symbols-outlined">
                                local_bar
                            </span>
                        Drinks</a>
                    <?php else: ?>
                        <a class="sidebar-menu-items" href="#">
                            <span class="material-symbols-outlined">
                                local_mall
                            </span>
                        Meus pedidos</a>
                    <?php endif; ?>
                </div>
                <form action="/logout" method="GET" class="logout-form">
                    <button type="submit" class="logout-btn"> Sair <span class="material-symbols-outlined">
                        logout
                    </span></button>
                </form>
            </div>
        </aside>
        <main>
            <div class="main-container">
                <div class="view-container">
                    <?php require $view ?>
                </div>
            </div>
        </main>
    </body>
</html>